apiVersion: v1
kind: Service
metadata:
  name: meditrack-backend-service
  labels:
    app: meditrack-backend
spec:
  selector:
    app: meditrack-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP