apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  labels:
    app: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.frontend.port }}
  type: LoadBalancer